### ISSUE TITLE
No idea why simply writing a return "Hello World" doesn't work.

### ISSUE THREAD

**Issue by Jianyi-Ren** [rmotr-curriculum/pyp-class-questions#13]
"An error occurred while executing your code" is what I got

**Comment by martinzugnoni** [comment]
There seems to be a problem in the external service we use to execute the code. Can you please try executing it again? If it keeps failing please let us know. Thanks!

**Comment by Jianyi-Ren** [comment]
Still not working here:(

**Comment by martinzugnoni** [comment]
I've just messaged you by Slack. Please take a look. :)

**Comment by corginomics** [comment]
I'm getting the same error too

**Comment by martinzugnoni** [comment]
We are aware of some issues the service we use to run the code is having at
the moment. We will try to contact them early tomorrow to fix it. Sorry for
that 🙏

El Tuesday, July 5, 2016, corginomics notifications@github.com escribió:

> I'm getting the same error too
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/rmotr-curriculum/pyp-class-questions/issues/13#issuecomment-230642750,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABGh9TwSqEaQnJMHcTvc3dOQh29bfEXDks5qSvlCgaJpZM4JEm3v
> .

## 

Martín Zugnoni.-
