### ISSUE TITLE
Modifying an exception that has already occurred.

### ISSUE THREAD

**Issue by gorrog** [rmotr-curriculum/pyp-class-questions#14]
In my code I have the following (which may be a poor way of doing it):
 except ValueError as e:
                #it's neither an int or a float
                raise ValueError("not a valid number string")

It seems silly to except a ValueError, ignore it, and then create a new ValueError. Is there a way to change the message of the existing ValueError e?

**Comment by santiagobasulto** [comment]
I believe there's no need of changing the message. In any case, what you do seems correct:

``` python
try:
    int('nothing')
except ValueError:
    raise ValueError('My custom message')
```
