### ISSUE TITLE
Failed in every test

### ISSUE THREAD

**Issue by greatestfactor489** [rmotr-curriculum/pyp-class-questions#17]
Can someone look at my code and see where I have errors? I tested all possible inputs and it seems to work for me. Am I missing something? 
[str2num.txt](https://github.com/rmotr-curriculum/pyp-class-questions/files/353136/str2num.txt)

**Comment by martinzugnoni** [comment]
Can you please post here which is the error you are getting when you execute your code? I'm wondering if you code is wrong or there's something bad happening in the code execution platform.

**Comment by greatestfactor489** [comment]
So it seems i fixed half of it not knowing that I had to return the number values. 
*Edit: I just updated my code in the .txt file.
Here's what it shows: 

test_cast_invalid_data_type (**main**.String2NumberTestCase) ... FAIL
test_cast_invalid_string_value (**main**.String2NumberTestCase) ... FAIL
test_cast_string_into_float (**main**.String2NumberTestCase) ... ok
test_cast_string_into_integer (**main**.String2NumberTestCase) ... ok

# 

## FAIL: test_cast_invalid_data_type (**main**.String2NumberTestCase)

Traceback (most recent call last):
  File "/usercode/file.py", line 50, in test_cast_invalid_data_type
    string2number(True)
AssertionError: ValueError not raised

# 

## FAIL: test_cast_invalid_string_value (**main**.String2NumberTestCase)

Traceback (most recent call last):
  File "/usercode/file.py", line 46, in test_cast_invalid_string_value
    string2number('invalid-value')
AssertionError: ValueError not raised

---

Ran 4 tests in 0.000s

FAILED (failures=2)

**Comment by martinzugnoni** [comment]
Ok, there should be something wrong in you solution, because the tests seems to be running well. 
If at some point you get stuck with your solution, share the code with us here so we can give you some extra hints. Thanks!
