### ISSUE TITLE
Clean Solution format_datetime function

### ISSUE THREAD

**Issue by professor042** [rmotr-curriculum/pyp-class-questions#18]
I got this to work, but I'm sure there must be a better solution utilizing more of the built-in datetime formatting capabilities, but I'm not very used to the documentation that Python has.  Can someone post their solution if it is cleaner than the following?

from datetime import date
from datetime import datetime
from datetime import time
def format_datetime(dt):

```
def dow(dt):
    days=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", 
        "Sunday"]
    day_number = dt.weekday()
    return days[day_number]

def moy(dt):
    months = ["January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"]
    month_number = dt.month-1
    return months[month_number]

def dnum(dt):
    if dt.day < 10:
        return "0" + str(dt.day)
    else:
        return str(dt.day)

def dsffx(dt):
    if dt.day == 1:
        return "st"
    elif dt.day == 2:
        return "nd"
    elif dt.day == 3:
        return "rd"
    else:
        return "th"

def dtime(dt):
    return dt.time().strftime("%H:%M")

str_date = dow(dt)+ " " + moy(dt) + " " + dnum(dt) + dsffx(dt) + ", "
str_date += str(dt.year) + " at " + dtime(dt) + " hs"
return str_date
```

**Comment by martinzugnoni** [comment]
You should probably take a look at the `datetime.strftime` function.

Documentation: https://docs.python.org/2/library/time.html#time.strftime

Something similar to this should work: `dt.strftime("%A %B %dth, %Y at %H:%M hs")`

**Comment by nicolas-siplis-zz** [comment]
If you wanna make it work on days not ending on 'th', here's my shot at it:

```
def format_datetime(dt):
    a = dt.strftime("%d")
    idx = int(a) - 1
    endings = ['st','nd','rd']
    try:
        a += endings[idx]
    except IndexError:
        a += 'th'
    return dt.strftime("%A %B ") + a + dt.strftime(", %Y at %H:%M hs")
```

**Comment by professor042** [comment]
Very nice - thanks. I knew there was probably a better way, but figured I
could use some practice with my own solution anyway.

Sent via Android phone.

**Comment by taqpol** [comment]
Is string formatting or string concatenation more "pythonic"? I used formatting for my problem, and performance is not really an issue for something like this, so which is better for readability?
