### ISSUE TITLE
Hello world code

### ISSUE THREAD

**Issue by bheenigarg** [rmotr-curriculum/pyp-class-questions#19]
I can't seem to figure out why my code is throwing an error. Please help. Thanks.

**Comment by martinzugnoni** [comment]
Can you please share your partial solution so we can take a look at the code? thanks!

**Comment by bheenigarg** [comment]
def hello_world():
     print('"Hello World"')

hello_world()

**Comment by cs-cordero** [comment]
@bheenigarg As explained in the instructions, your function needs to just simply return "Hello World", not print it.
