### ISSUE TITLE
Ideal answer?

### ISSUE THREAD

**Issue by taqpol** [rmotr-curriculum/pyp-class-questions#21]
Being unable to raise an exception for attribute errors, I decided to manually raise one if the variable-length argument list provided was less than length 1, which doesn't actually qualify as an error since the sum() function will just return 0 if the argument it is provided is empty. I'm curious about the answer that actually allows for a true exception to be raised for attribute errors.

**Comment by taqpol** [comment]
If it helps, here is what I submitted. As you can see, the attribute error was manually raised just so that I could pass the test. Normally, this code should only raise a type error if someone passes non-numeric values to the function. 

```
def sum_multiple(*vals):
    if len(vals) < 1:
        raise AttributeError
    else:
        return sum(vals)
```

**Comment by cs-cordero** [comment]
This is how I did this as well. Would be good to know other ways of doing this.
