### ISSUE TITLE
Computing length of string/list without len?

### ISSUE THREAD

**Issue by charliegphan** [rmotr-curriculum/pyp-class-questions#24]
Hi, I've read through the assigned reading and I'm still confused as to how to compute a string or list length without using the len() method. How should I even start going about creating a function that does that? Thank you!

**Comment by santiagobasulto** [comment]
Charlie! A list is just a sequence of characters. The string `"hello"` is basically `['h', 'e', 'l', 'l', 'o']`. You can do something like:

``` python
for char in 'hello':
    print(char)
```

So, this assignment is almost the same as counting the elements in a list.

**Comment by thezerobyte** [comment]
So this works for me but it doesn't work with your unit tests....

def length(string):
    length=0
    for x in string:
        length+=1
    print(length)

**Comment by santiagobasulto** [comment]
What error are you getting @thezerobyte?

**Comment by thezerobyte** [comment]
test_length_empty_string (**main**.LengthTestCase) ... FAIL
test_length_multiple_words (**main**.LengthTestCase) ... FAIL
test_length_single_word (**main**.LengthTestCase) ... FAIL

# 

## FAIL: test_length_empty_string (**main**.LengthTestCase)

Traceback (most recent call last):
  File "/usercode/file.py", line 23, in test_length_empty_string
    self.assertEqual(length(''), 0)
AssertionError: None != 0

# 

## FAIL: test_length_multiple_words (**main**.LengthTestCase)

Traceback (most recent call last):
  File "/usercode/file.py", line 17, in test_length_multiple_words
    self.assertEqual(length('hello world'), 11)
AssertionError: None != 11

# 

## FAIL: test_length_single_word (**main**.LengthTestCase)

Traceback (most recent call last):
  File "/usercode/file.py", line 20, in test_length_single_word
    self.assertEqual(length('hello'), 5)
AssertionError: None != 5

---

Ran 3 tests in 0.000s

FAILED (failures=3)

**Comment by thezerobyte** [comment]
seems you name everything file. If I go to python command line and go:
import file (name of file)
from file import length
I can do length('test') and get result

**Comment by santiagobasulto** [comment]
@thezerobyte you have to return the value! If a function doesn't return (at any point), the default value returned is None. print is not the same as returning.
