### ISSUE TITLE
Does it specifically have to be two nested _LIST_ comprehensions?

### ISSUE THREAD

**Issue by Psy-Kosh** [rmotr-curriculum/pyp-class-questions#27]
Is it okay to have the inner thing contain an "any" expression containing a generator expression? (As in, it will work, but I'm not sure if that's in the spirit of the assignment)

**Comment by santiagobasulto** [comment]
hey Josef! Do you mean the `any()` stdlib function? https://docs.python.org/3/library/functions.html#any

**Comment by Psy-Kosh** [comment]
Yeah. More to the point, I used a generator expression inside of it. (Well, you can see what I submitted (right?)) But yeah, inside the any call, I used a generator expression rather than list comprehension. really the only syntactic difference would be I didn't wrap that expression in brackets, but of course that's the difference between actually constructing the list and then applying any to it (then discarding the list) vs the list not being constructed. (the outer list was still generated via comprehension))

You know what I mean. (Sorry, seem to have mild cold or such, may be a bit out of it.) But yeah, I simply wasn't sure if what I did counted as within the "spirit" of the assignment or not. That's all.

**Comment by santiagobasulto** [comment]
Yes, I have a solution using `any()` and other using `all()`. Can you share your solution here? I do have access on learn.rmotr.com to see all the solutions but it's not implemented in a nice way yet (work in progress).

**Comment by Psy-Kosh** [comment]
``` python
def divisible_numbers(nums, divs):
    return [n for n in nums if not any(n%d for d in divs)]`
```

**Comment by Psy-Kosh** [comment]
Eeep, hit wrong button there. Sorry about that.

**Comment by Psy-Kosh** [comment]
(Hrm... looks like code formatting is weird here and ignores newlines. That could be annoying potentially)

**Comment by santiagobasulto** [comment]
Three backquotes + the python word

``` python
def hello():
    pass
```

**Comment by santiagobasulto** [comment]
Yep, same solution as I have. You can of course use brackets to turn the list comprehension in a generator comprehension, but it's just syntax, as you said. Good stuff!

**Comment by Psy-Kosh** [comment]
Ah, thank you.
