### ISSUE TITLE
The interface

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/pyp-class-questions#3]
I get how to submit the code, but how do I utilize the test cases option on the first question.

**Comment by rosiecakes** [comment]
@monkeyarms88 I believe the test is only used to validate the submitted code and to help show us what the question is asking. We don't use it directly.

**Comment by ghost** [comment]
so they give example answers that we see if our code matches for?

**Comment by santiagobasulto** [comment]
As @rosiecakes said, we use the TestCase to validate your solution. The code is executed by learn appending your solution to the set of tests.
