### ISSUE TITLE
List comprehension

### ISSUE THREAD

**Issue by jaroldwong** [rmotr-curriculum/pyp-class-questions#30]
The exercises under Collections requires list comprehension. I didn't remember reading them in the reading material. Am I missing something?

**Comment by santiagobasulto** [comment]
You're right @jwong, I've just fixed it: https://github.com/rmotr-curriculum/pyp-class/commit/5f9a9230c795b427849da28a04b50e429bb37886

Should be updated now. Thanks for reporting it!
