### ISSUE TITLE
isinstance(True, int)

### ISSUE THREAD

**Issue by duddles** [rmotr-curriculum/pyp-class-questions#5]
I'm curious about the logic for how this is evaluated

**Comment by martinzugnoni** [comment]
Yeah, that's a very interesting edge case. Because in Python boolean values are subclasses of integers. You can try to find some work around by checking if the given value is included in `[True, False]` and return the proper String in that case.

**Comment by rosiecakes** [comment]
These helped me:
http://stackoverflow.com/questions/1549801/differences-between-isinstance-and-type-in-python
http://python-reference.readthedocs.io/en/latest/docs/functions/isinstance.html
