### ISSUE TITLE
Following code runs for me, but I get an undisclosed error on submission.

### ISSUE THREAD

**Issue by bdauer** [rmotr-curriculum/pyp-class-questions#7]
from **future** import division

class Calculator(object):

```
@staticmethod
def add(x, y):
    return x + y

@staticmethod
def subtract(x, y):
    return Calculator.add(x, (y * -1))

@staticmethod
def multiply(x, y):
    return x * y

@staticmethod
def divide(x, y):
    return x / y
```

**Comment by lana519** [comment]
I'm guessing it's the import statement causing the issue.  You can get decimals by just converting those ints to floats:
return float(x) / float(y)
That makes it work, but now I'm uncertain if that's the correct way of going about it.
