### ISSUE TITLE
ValueError?

### ISSUE THREAD

**Issue by whieronymus** [rmotr-curriculum/pyp-class-questions#9]
Anyone else having trouble returning the proper type of error? First off, none of the reading covered Try/Except at all, and second Have the use cases are returning a TypeError not a ValueError anyways. I feel like I am very comfortable with all of the reading materials but I don't understand why I'm struggling with the Code Questions.

**Comment by santiagobasulto** [comment]
Hey Will! Can you show us an example?

**Comment by zapplecat** [comment]
While Try/Except might be a good option, I believe this is solvable using the str.isdigit method without escaping out of errors.

**Comment by whieronymus** [comment]
This is the closest I've come to getting the string2number question:

```
def string2number(a_string):
    if a_string.isdigit():
        return int(a_string)
    elif isinstance(float(a_string), float):
        return float(a_string)
    else:
        raise ValueError("Not a valid number string")
```

Here are the results:
test_cast_invalid_data_type (**main**.String2NumberTestCase) ... ERROR
test_cast_invalid_string_value (**main**.String2NumberTestCase) ... ok
test_cast_string_into_float (**main**.String2NumberTestCase) ... ok
test_cast_string_into_integer (**main**.String2NumberTestCase) ... ok

# 

## ERROR: test_cast_invalid_data_type (**main**.String2NumberTestCase)

Traceback (most recent call last):
  File "/usercode/file.py", line 30, in test_cast_invalid_data_type
    string2number(True)
  File "/usercode/file.py", line 3, in string2number
    check_float = a_string.split()
AttributeError: 'bool' object has no attribute 'split'

---

Ran 4 tests in 0.001s

FAILED (errors=1)

**Comment by whieronymus** [comment]
The test case that uses the 'False' arguement is returning an AttributeError, and I don't know how to handle it. If someone could point me where I might find the answer either in the reading or a site I could study that would be great! 

Thanks!

**Comment by martinzugnoni** [comment]
@whieronymus as far as I can see in the learn platform, you could already resolve the assignment, right? Do you still have any doubts about it? Just let me know. Thanks.
